### ISSUE TITLE
question on fromPromise

### ISSUE THREAD

**Issue by vonovak** [mobxjs/mobx-utils#107]
Hi! I have written a test where I have used

```
fetchResult.then(
      result => {
        expect(result).toEqual(...)
      }
    );
```

When I rewrite it as 

```
const result = await fetchResult
expect(result).toEqual(...)
```

It also works - Is that a coincidence, or is that supported? For a second I though babel might transpile the await call into then() but I don't think that is the case, at least according to babel repl. Thanks!

**Comment by daedalus28** [comment]
Sorry, I'm not following. The question seems unclear. What is happening? Also, at first glance, this seems like a question for the babel repo.

**Comment by vonovak** [comment]
@daedalus28 I updated the description, sorry :)

**Comment by daedalus28** [comment]
@vonovak that is expected. It's how `await` works - it's basically syntactical sugar for `.then` (although that is an oversimplification for sure). Depending on your babel settings, it may or not be compiled (if it is, it's likely using a generator alternative using something like `regenerator`), but the native JS feature of `await` should generally work to allow you to unnest promise `.then` chains.

So to directly answer your question, yes that should be supported. All of the promise related/async things in mobx-utils should work with `async/await` - not because we actively wrote support for it, but because that's the nature of the language feature.

**Comment by vonovak** [comment]
@daedalus28 sounds good, and after I checked the source code I see how it works (ie. `fromPromise` returns a promise). I feel like the docs should be improved though, because they make it sound more like the returned value is not a promise, but rather something that wraps the promise:

> fromPromise takes a Promise and returns an object with 3 observable properties that track the status of the promise. The returned object has the following observable properties: (and then 2 observable properties are listed)

I'll try to ship over a PR that improves it

**Comment by vonovak** [comment]
@daedalus28 related: https://github.com/mobxjs/mobx-utils/pull/108
