### ISSUE TITLE
computed fromPromise with nested promises does not reevaluate when observable changes

### ISSUE THREAD

**Issue by andrewgadziksonos** [mobxjs/mobx-utils#122]
Hello there!  I'm running into this issue where I have certain computed values that are promises of promises, filtered on observables, which are not reevaluated when the observables it depends on changes.  Here's an example,

```
class CustomerStore {
  @observable selectedCustomerId = "";
  @observable selectedHouseholdId = "";

  @computed
  get customer() {
    return this.selectedCustomerId
      ? fromPromise(api.getCustomerById(this.selectedCustomerId))
      : fromPromise.resolve(null);
  }

  @computed
  get customerRegisteredProducts() {
    return fromPromise(
      this.customer.then(customer => {
        return api.getCustomerRegisteredProducts(customer.identity.id).then(
          action(products => {
            this.selectedHouseholdId = products.map(p => p.householdId).shift();
            return products;
          })
        );
      })
    );
  }

  @computed
  get customerProducts() {
    return fromPromise(
      this.customerRegisteredProducts.then(registeredProducts => {
        return registeredProducts.filter(
            rp => rp.householdId === this.selectedHouseholdId
          );
      })
    );
  }
}
```

`this.selectedHouseholdId` is updated by a `<select>` field in the UI, but I noticed that the list of `customerProducts` is not reevaluated when that changes.  What am I doing wrong?

Thanks for the help,

Andrew

**Comment by mweststrate** [comment]
That behavior is correct, `@computed` only tracks what happens during its own computation, not stuff that happens in the future (like) `then` resolvers.
You could restructure this like the follow, so that the computation of the returned promise depends on both the houseHoldId and the registeredProducts (computed values don't base their computation on what happens *after* returning something, because, well that is something that happened *after* the computation, so apparently the outcome of the computation didnt depend on it)

```javascript
  @computed
  get customerProducts() {
    const houseHoldId = this.selectedHouseHoldId
    return fromPromise(
      this.customerRegisteredProducts.then(registeredProducts => {
        return registeredProducts.filter(
            rp => rp.householdId === householdId
          );
      })
    );
  }
```

You also might want to check out this library: https://github.com/danielearwicker/computed-async-mobx/
