### ISSUE TITLE
Difference between createTransformer and computedFn

### ISSUE THREAD

**Issue by flipchart** [mobxjs/mobx-utils#199]
I have the same question as this one which unanswered on SO

https://stackoverflow.com/q/55810836/789683

> What is the difference between mobx's createTransformer and mobx-utils computedFn?
> 
> Sometimes there is overlap between things in mobx and mobx-utils (ie whenWithTimeout) but when I've seen that in the past the later has been marked deprecated. Looking into the implementation of computedFn, it seems like it could be doing something additional to observe the arguments passed into the computedFn() result. I'm not sure though.

From what I can see in the source, createTransformer only takes 1 argument, while computedFn takes multiple arguments. Can you confirm if this is the only difference? Also, if I have a function with only 1 parameter, which is the preferred function?

**Comment by mweststrate** [comment]
`createTransformer` doesn't need a 'host' to store it's state in. If you can leverage `computedFn`, I would.

**Comment by DavraYoung** [comment]
computedFn uses DeepMap to memoize its parameters, whereas createTransformer mutates the parameters to assign the id and thus maintains its cache. There may be some potential issues with this, for example: transformer({...observable}) will always recompute, because the reference is always different. That's why its better to use computedFn
