### ISSUE TITLE
fromPromise returns value as undefined during pending state, is this correct?

### ISSUE THREAD

**Issue by will-stone** [mobxjs/mobx-utils#99]
Hi. First-off, thank-you very much for MobX and MobX-Utils; I'm learning new tips and tricks every day. I've recently switched a lot of my fetchers over to use fromPromise and it has greatly reduced some repetition in my code. One thing I've noticed is that [observable].value will become `undefined` when the promise is in `pending` state, despite me setting the default value. Is this correct? Or should the value only be altered on fulfilled? For example:

```
class DataStore {
  constructor(rootStore) {
    this.root = rootStore
    extendObservable(this, {
      test: fromPromise.resolve([]),
      testComputed: computed(() => this.test.value),
    })
  }

  loadTest = action('Load test', function() {
    this.test = fromPromise(getTest())
  })
}

-------------------------------------------

class Example extends Component {
  componentDidMount() {
    this.props.dataStore.loadTest()
  }
  render() {
    const { dataStore } = this.props
    console.log(dataStore.testComputed)
    ...
  }
}
export default inject('dataStore')(observer(Example))
```

Console:

```
[]
undefined
['example','data','response']
```

If this is by design, do you mind giving a brief description of why?

NB, I'm using this in a Create-React-App environment and so can't use decorators.

**Comment by mweststrate** [comment]
I think your problem is that you use `DidMount` instead of `WillMount`.
DidMount fires only after the first render, so until that time `this.test`
is not set

Op di 19 dec. 2017 om 12:23 schreef Will Stone <notifications@github.com>:

**Comment by will-stone** [comment]
Hmmm... from [previous](https://daveceddia.com/where-fetch-data-componentwillmount-vs-componentdidmount/) research, I thought fetchers (state changers) should be in `didMount`. That aside, it's asynchronous, the console.log is simply firing on changes to the `testComputed` observable. No matter where the call is that fetches the data, the value will still go through
```
[]
undefined
['example','data','response']
```
No?

**Comment by mweststrate** [comment]
Sorry, missed the notification @will-stone. 

Anyway, this is (inconveniently) behaving as expected the states of `this.test`  will be:
1. `undefined`, as long as `fromPromise.resolve([])` didn't resolve (but you probably won't notice this one
2. `[]` when the above resolved
2. `undefined`, because there is a new, unresolved promise in `test` which doesn't have a value yet. `test` no longer refers to the original promise here.
3. `['example','data','response']` once that promise is resolved 

expressing it a bit differently and actually checking the state of the promise, and return something based on that:

For example:
```
testComputed: computed(() => this.test.state === "pending" ? [] : this.test.value)
``` 

or neater, use the `.case` method:

``` 
computed(() => this.test.case({
  pending:   () => []
  rejected:  error => error
  fulfilled: value => value
}))
```

**Comment by will-stone** [comment]
Ah, ok. I've been using computed more often recently so will give that a go. Thanks.
